-function(){"use strict";var e=function(a){return"gwd-page"==a.tagName.toLowerCase()||"gwd-page"==a.getAttribute("is")},f=function(a){if(e(a))return a;for(;a&&9!=a.nodeType;)if((a=a.parentElement)&&e(a))return a;return null};var g=function(a,b,c){var d=function(k){a.removeEventListener(b,d);c(k)};a.addEventListener(b,d)};var h=function(a){a||(a="");return/^[\s\xa0]*$/.test(a)};
document.registerElement&&document.registerElement("gwd-imagebutton",{prototype:Object.create(HTMLElement.prototype,{createdCallback:{value:function(){for(var a;a=this.firstChild;)this.removeChild(a);this.c="gwd_imagebutton_"+(2147483648*Math.random()|0);this.e="ontouchstart"in window||0<window.navigator.MaxTouchPoints||0<window.navigator.msMaxTouchPoints;this.a=document.createElement("div");this.a.className=this.c;this.appendChild(this.a);this.d=null;this.i=this.b=!1;this.k=document.createElement("img",
"gwd-image");this.j=document.createElement("img","gwd-image");this.h=document.createElement("img","gwd-image");this.f=document.createElement("div","gwd-page");this.g=this.handleClick_.bind(this);this.l=this.handleLoad_.bind(this);this.style.display="inline-block";this.style.padding=0;this.a.style.backgroundRepeat="no-repeat";this.a.style.width="100%";this.a.style.height="100%"},enumerable:!0},attachedCallback:{value:function(){this.a.addEventListener("click",this.g,!1);if("function"==typeof this.gwdLoad&&
"function"==typeof this.gwdIsLoaded&&!this.gwdIsLoaded()){var a=f(this),b=a&&"function"==typeof a.gwdIsLoaded;(!a||b&&a.gwdIsLoaded())&&this.gwdLoad()}},enumerable:!0},detachedCallback:{value:function(){this.a.removeEventListener("click",this.g,!1)},enumerable:!0},attributeChangedCallback:{value:function(a){var b=this.getAttribute(a);switch(a){case "position":b?this.a.style.backgroundPosition=b:this.setAttribute(a,"center");break;case "scaling":b?this.a.style.backgroundSize=b:this.setAttribute(a,
"auto");break;case "up-image":this.setSource_(this.k,b);break;case "over-image":this.e||this.setSource_(this.j,b);break;case "down-image":this.setSource_(this.h,b);break;case "disabled":this.b=this.hasAttribute("disabled")&&"false"!=this.getAttribute("disabled");this.installStyle_();this.a.style.cursor=this.b?"default":"pointer";break;case "bgcolor":this.a.style.backgroundColor=b}},enumerable:!0},setSource_:{value:function(a,b){h(b)?this.installStyle_():(a.setAttribute("source",b),this.loadImages_())},
enumerable:!1},gwdIsLoaded:{value:function(){return this.i}},gwdLoad:{value:function(){for(var a=["bgcolor","position","scaling","disabled"],b=0;b<a.length;b++)this.attributeChangedCallback(a[b],null,null);h(this.a.style.backgroundColor)&&(this.a.style.backgroundColor=window.getComputedStyle(this).backgroundColor);this.loadImages_()},enumerable:!0},loadImages_:{value:function(){var a=document.createElement("div","gwd-page");a.style.display="none";a.appendChild(this.k);this.e||a.appendChild(this.j);
a.appendChild(this.h);this.f=a;g(a,"attached",a.gwdLoad.bind(a));g(a,"pageload",this.l);this.a.appendChild(this.f)},enumerable:!1},handleLoad_:{value:function(a){if(a){if(a.target===this.f){this.i=!0;this.installStyle_();var b;b=document.createEvent("Event");b.initEvent("ready",!0,!0);this.dispatchEvent(b)}(b=a.target.parentNode||a.target.parentElement)&&b.removeChild(a.target);a.target=null}},enumerable:!1},handleClick_:{value:function(a){this.b&&a.stopPropagation()},enumerable:!1},installStyle_:{value:function(){this.uninstallStyle_();
var a=this.getAttribute("up-image"),b=this.getAttribute("over-image"),c=this.getAttribute("down-image"),d="";h(a)||(d+="."+this.c+' { background-image: url("'+a+'"); }');h(b)||this.b||this.e||(d+="."+this.c+':hover { background-image: url("'+b+'"); }');h(c)||this.b||(d+="."+this.c+':active { background-image: url("'+c+'"); }');a=d;c=null;c=document;-1!=navigator.userAgent.indexOf("MSIE")&&c.createStyleSheet?(c=c.createStyleSheet(),c.innerHTML=a):(b=c.getElementsByTagName("head")[0],b||(d=c.getElementsByTagName("body")[0],
b=c.createElement("head"),d.parentNode.insertBefore(b,d)),c=c.createElement("style"),c.innerHTML=a,b.appendChild(c));this.d=c},enumerable:!1},uninstallStyle_:{value:function(){if(this.d){var a=this.d;(a=a.ownerNode||a.owningElement||a)&&a.parentNode&&a.parentNode.removeChild(a);this.d=null}},enumerable:!1},toggleEnable:{value:function(){(this.b=!this.b)?this.setAttribute("disabled","true"):this.removeAttribute("disabled")},enumerable:!0},setImages:{value:function(a,b,c){this.setAttribute("up-image",
a);this.e||this.setAttribute("over-image",b||"");this.setAttribute("down-image",c||"")},enumerable:!0}})});}()
